### PR TITLE
format JSON listings

### PR DESCRIPTION
**Pull request by line-o**

### CODE REVIEW

**Review by joewiz — APPROVED** [review]

**Comment by joewiz** [comment]
@line-o I'm curious, what tool did you use to format the JSON? (I use oXygen's format & indent.)

**Comment by line-o** [comment]
@joewiz I really just did it by hand in this case. :)

**Comment by line-o** [comment]
Is there something off?

**Comment by joewiz** [comment]
Ah! I had assumed you'd used a tool and was really, er, just curious. 

This is the kind of thing that strikes me as lintable, but rigging such a checker-and-fixer up is beyond my skills.

**Comment by line-o** [comment]
Ah! In that case [prettier](https://prettier.io) is popular for automatically formatting code.

**Comment by joewiz** [comment]
That would be cool! As with JSON, oXygen can format XQuery, though as you might imagine it doesn't necessarily match everyone's stylistic preferences...

**Comment by line-o** [comment]
Yes, I can, as does XQLint. There is also the XQDoc rules on formatting XQuery.
I think having a shared formatting rule - automatically applied when committing code - would be a major milestone.

**Comment by line-o** [comment]
But we digress :)

**Pull request merged**
